[tool.ruff]
# Mesmo comportamento do Black para compatibilidade
line-length = 120
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
